namespace Stats
{
    public enum StatType
    {
        hp,
        hpRegen,
        damage,
        attackSpeed,
        lifeSteal,
        critChange,
        critDamage,
        armor,
        dodge,
        knockback,
        damageReflection,
        speed,
        luck,
        harvesting,
        hpRate,
        hpRegenRate,
        damageRate,
        attackSpeedRate,
        lifeStealRate,
        critChangeRate,
        critDamageRate,
        armorRate,
        dodgeRate,
        knockbackRate,
        damageReflectionRate,
        speedRate,
        luckRate,
        harvestingRate
    }
}